hydra:
  run: 
    # Set the output directory to be the same as script's directory
    dir: .
  output_subdir: .hydra

defaults:
  - dataset: mnist
  - model: flow_jit_mnist
  - training: default
  - sampling: default
  - _self_

# Global settings
device: 'cuda'
experiment_name: flow_jit_mnist
seed: 42
resume_from_run_id: null